### ISSUE TITLE
Crazy export value this morning

### ISSUE THREAD

**Issue by larserhardsen** [UtilitechAS/amsreader-firmware#512]
**Describe the bug**
First of all, thank you for an awesome piece of software!

This morning, the AMSreader shows some quite crazy calculations on the export side ... I think I exported 5-6 kWh yesterday, and today it's unsigned Int.MaxValue day or something ;-) An upgrade from 2.2.9 to 2.2.12 did not solve anything.
Is it the meter itself or AMSreader?

**Screenshots**
![image](https://user-images.githubusercontent.com/3054735/229425671-8b38fc81-f739-46d3-988f-c42bb110a3c1.png)
![image](https://user-images.githubusercontent.com/3054735/229426628-b65ac793-a70e-4e9d-bcaa-d2fba26db44d.png)

**Hardware information:**
 - Country: Denmark
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-K+

**Relevant firmware information:**
 - Version: 2.2.9->2.2.12
 - MQTT: yes
 - MQTT payload type: Home Assistant
 - HAN baud and parity: 2400 8N1
 - ENTSO-E API enabled: yes

**Comment by gskjold** [comment]
Did you get this bar before or after upgrading?

**Comment by larserhardsen** [comment]
It was there before the upgrade - I saw the weird number in HA and went to the AMSreader UI, and saw that an upgrade was available, so I upgraded.

**Comment by gskjold** [comment]
OK, this issue should be fixed with the new version, but it does not rectify old calculation errors. There is a small guide here to edit the dayplot here: https://amsleser.no/blog/post/28-correcting-stored-values-by-editing-the-configuration-file

Or you can unzip and upload this cfg file under "Backup & restore" on the status page to reset the graph:
[reset-dayplot.cfg.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11135372/reset-dayplot.cfg.zip)

**Comment by gskjold** [comment]
Note that it will reset both graphs. If you want to keep month, first option of editing is suggested

**Comment by larserhardsen** [comment]
That's super, thank you for the quick response!
