### ISSUE TITLE
2.20.0 very unstable

### ISSUE THREAD

**Issue by Sommerdal-ufm** [UtilitechAS/amsreader-firmware#595]
**Describe the bug**
A clear description of what the bug is.
Web interface very slow.
When answering it shows that it is recently restarted and current hour cost is 0.
![Screenshot_2023-06-14-18-50-55-82](https://github.com/UtilitechAS/amsreader-firmware/assets/54624988/dcca22db-0157-46e4-a2a7-12cb1d087efc)

**To Reproduce**

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Hardware information:**
 - Country: [e.g. Norway]
 - Meter: [e.g. Aidon]
 - Encryption enabled [yes/no]
 - AMS reader: [e.g. Pow-U, ESP32 etc]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [e.g. 2.1.0]
 - MQTT: [yes/no]
 - MQTT payload type: [e.g. JSON]
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no]

**Additional context**

**Comment by ArnieO** [comment]
Strange issue, and nobody else has reported this.

- I understand this is a Pow-K+ that you have had running since around start of May - is that right?
- You are sure this started when you updated to 2.2.20? 
- No other changes in your Wifi network at or around the same time?
- Do you see any error blinks on the device (ref Firmware User Manual chapter 10)?
- Can you show us a screenshot of your config page?

**Comment by Sommerdal-ufm** [comment]
Pow-k - start of May - Correct

I never had this issue before 2.2.20.

It is only with 2.2.20 I've seen an uptime reset with no reason.

No change to network.

Haven't looked at device during problem.

I'll attach a screenshot in a while.


ons. 14. jun. 2023 19.08 skrev ArnieO ***@***.***>:

**Comment by ArnieO** [comment]
It could be there is an issue with the card for some reason (in which case we'll send you a replacement). We have had very few suck issues - but it cannot be ruled out.

But if it started with the firmware update it would be a strange coincidence if it is HW related. And we have many users on v2.2.20 running it without issues. So... looking forward to your screenshot!

What is the reboot reason it states on the Info-page?
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/27da6a0b-7606-483e-a1c8-e77d7e12c11d)

**Comment by Sommerdal-ufm** [comment]
I dont think that the problem is HW related.

I've attached the required screenshots.
![Screenshot_2023-06-15-18-11-42-81](https://github.com/UtilitechAS/amsreader-firmware/assets/54624988/9a4d772c-c178-4201-9c15-715fa93e9e25)
![Screenshot_2023-06-15-18-10-40-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UtilitechAS/amsreader-firmware/assets/54624988/7d632611-74aa-48ae-9fcf-ded7d8f26433)

**Comment by gskjold** [comment]
There isn't really much code change in 2.2.20 compared to 2.2.19, it's mostly just user interface which does not affect firmware stability. Reboot with reason Vbat power on reset sounds like there was a power cycle on the chip to me.

**Comment by Sommerdal-ufm** [comment]
That is also what I thought.
But I had it twice in 2-3 days, so I assumed it could be a bug.
Feel free to close.

fre. 16. jun. 2023 09.11 skrev Gunnar Skjold ***@***.***>:

**Comment by ArnieO** [comment]
We have seen some boards that start rebooting by themselves like that - with a shorter or longer period. 

I have long-term tested identical boards with identical firmware and identical setup in my Kamstrup meter, and have concluded that there is a HW problem on some ESP modules. The board I have been using for almost a year now reboots a few times per day like that, but it is not often enough to be a real problem for me. 
That is what you see here, 1 hour uptime and same reboot as your board: https://github.com/UtilitechAS/amsreader-firmware/issues/595#issuecomment-1593081526
The problem has not become worse since I started using the board permanently in August last year. 

If this is a problem to you, please email us at post@amsleser.no to get a replacement board.

**Comment by Sommerdal-ufm** [comment]
Thanks. But I really dont consider it a problem yet.
If the problem increases I'll return. 👍

fre. 16. jun. 2023 13.10 skrev ArnieO ***@***.***>:
