### ISSUE TITLE
Wrong voltage / amperage

### ISSUE THREAD

**Issue by 1968-Larry** [UtilitechAS/amsreader-firmware#629]
**Describe the bug**
After upgrade last week Voltage shows *10 and Amperage *100. Shows same on gui and mqtt.

**Screenshots**

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/4251986/5fe7147d-c479-4c17-a48c-4392a5775ceb)

**Hardware information:**
 - Country: Swedeb
 - Meter: Manufacturer: Kaifa, Model: MA304H4
 - Encryption enabled [yes/no]
 - AMS reader: ESP32
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [v2.2.21]
 - MQTT: yes
 - MQTT payload type: [JSON]
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [none]
 - ENTSO-E API enabled: [yes]

**Comment by gskjold** [comment]
This happenes when scaling is not provided by the meter. Please set multipliers under the meter configuration to adjust for this.

Before 2.2.16, a multiplier was applied in firmware, but have been removed since it is not always the same.

Same as https://github.com/UtilitechAS/amsreader-firmware/issues/558
