### ISSUE TITLE
Website information about LandisGyr E360

### ISSUE THREAD

**Issue by ewxl** [UtilitechAS/amsreader-firmware#647]
**Describe the bug**
The website states both that the unit is verified to work with Landis&Gyr E360, but also in the description, that there is a problem. This was misleading so I placed an order and now have one that doesn't seem to be able to boot correctly when connected to the meter. My Pow-P1 is now stuck in a reboot-loop, so it seems it is a power-issue.

1. It was first booted with power via USB and setup for my WiFi. 
2. After reboot, it was connected to the Wifi successfully. 
3. I there did a firmware upgrade to the latest available. 
4. After this, I connected it to my meter but here it starts rebooting.

**To Reproduce**
Connect Pow-P1 to Meter E360

**Expected behavior**
The unit should work as intended.

**Hardware information:**
 - Country: Sweden
 - Meter: Landis&Gyr E360
 - AMS reader: Pow-P1

**Relevant firmware information:**
 - Version: 2.2.22

**Comment by ArnieO** [comment]
We have indeed discovered a weakness in our design that causes it to go into a reboot loop on some individual meters (and all Kamstrup Omnia E-meter systematically). 

The issue is covered quite extensively in this thread: https://github.com/UtilitechAS/amsreader-firmware/issues/584

We know for a fact Pow-P1 runs well on a number of Landis Gyr E360 (it was in fact on the "test panel" when we designed it).

However - the important point for you is that we know how to fix this (ref the thread linked here above). 

**Please contact us at post@amsleser.no so we know who you are - and we will ship you a modified board that will not have this issue.**
