### ISSUE TITLE
How to connect the temp sensor DS18B20 to Pow-K+ ?

### ISSUE THREAD

**Issue by ielthbe** [UtilitechAS/amsreader-firmware#694]
How to connect the temp sensor DS18B20 to Pow-K+ ?
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/49042834/6828b2d0-a12e-497b-9202-e7c140dbfe90)
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/49042834/7c761d9d-ba93-4c68-8c52-f657773de569)

**Comment by ArnieO** [comment]
Well done!
Here is a sneak peek on the next version Pow-K that we will start selling when current stock is sold out, expected somewhere in Q1/24. We decided to include a footprint for DS18B20, and included the pullup resistor (R12; costs almost nothing), so that interested users can easily add a DS18B20. It is a relatively expensive component (unless you buy a cheap Chinese clone), so we think it is better that those who need it install it themselves.
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/3361e890-9d00-460e-983c-9b78790e688c)

**Comment by gskjold** [comment]
I might be wrong here, but using "+" from the external power source, doesn't that also apply +4.5 (or +5v in case of USB power) to the GPIO pin? Could burn out the GPIO?

**Comment by ArnieO** [comment]
> I might be wrong here, but using "+" from the external power source, doesn't that also apply +4.5 (or +5v in case of USB power) to the GPIO pin? Could burn out the GPIO?

I assume he is using a pullup resistor between 5V and GPIO.

This is how the optional sensor is implemented on the coming version of Pow-K:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/765bbb7f-9fc5-4cd9-9d83-3a846e4f2973)
