### ISSUE TITLE
Question: Sagemcom T210-D-r "Energienetze Steiermark"

### ISSUE THREAD

**Issue by cocoon77** [UtilitechAS/amsreader-firmware#718]
Hi,
could you please check if the Sagemcom T210-D-r also works with your Software.

**Hardware information:**
 - Country: Austria
 - Meter:  Sagemcom T210-D-r
 - Encryption enabled [yes]
 - AMS reader: don't have one yet, but ordered Pow-P1.

Here is a link for more informations about the device (sorry in german)
[https://github.com/debug-richard/sagemcom-dsmr](https://github.com/debug-richard/sagemcom-dsmr)
[Info from provider https://www.e-netze.at](https://www.e-netze.at/downloads-data/pdf.aspx?pdf=20240111_EN_Update%20Kundenschnittstelle%20Smart%20Meter_ID3884%20(01_2024)_V1.pdf)

thx for all your great work
Martin

**Comment by ArnieO** [comment]
The software is not the issue here, the important point is to select the right hardware. 

- Your first link says it transmits at 115 200 baud, meaning it is "P1 companion standard". 
- Your second link, from e-netze.at, also says that their Sagemcom model is "P1 companion standard".

So according to this, the Pow-P1 should be right for you.

(And I now suspect we have an error in this table: https://github.com/UtilitechAS/amsreader-firmware/wiki/Known-hardware-configurations )

**Comment by Noschvie** [comment]
https://www.e-netze.at/downloads-data/pdf.aspx?pdf=20240111_EN_Update%20Kundenschnittstelle%20Smart%20Meter_ID3884%20(01_2024)_V1.pdf

Have you had a look to this document?

**Comment by cocoon77** [comment]
> https://www.e-netze.at/downloads-data/pdf.aspx?pdf=20240111_EN_Update%20Kundenschnittstelle%20Smart%20Meter_ID3884%20(01_2024)_V1.pdf
> 
> Have you had a look to this document?

Yes thats the 2nd link in my post :)
