### ISSUE TITLE
Error in sensor configuration for two of the HA MQTT sensors

### ISSUE THREAD

**Issue by StarkJohan** [UtilitechAS/amsreader-firmware#798]
Low severity "bug".

There's an error in sensor configuration for two of the HA MQTT sensors. The warning from the HA log describes the issue as well as the solution pretty clearly as can be seen below.

_Entity **sensor.kamstrup_threshold** (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity **sensor.kamstrup_max** (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22_

**Comment by rogerthn2019** [comment]
+1

> 2024-05-23 16:34:22.153 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ams_cf58_threshold (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2024-05-23 16:34:22.154 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ams_cf58_max (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
