### ISSUE TITLE
2.3.5 and up breaks HAN data.

### ISSUE THREAD

**Issue by githubpassera** [UtilitechAS/amsreader-firmware#823]
**Describe the bug**
No data from HAN port 2.3.5+

Rolling back to 2.3.4 solves issue.
2.3.5 & 2.3.6
![image](https://github.com/user-attachments/assets/aad501d2-7b4d-4b2c-a368-a407effb02e4)

**Hardware information:**
 - Country: Sweden
 - Meter: Kaifa MA304H4
 - Encryption enabled no
 - AMS reader: ESP32

**Relevant firmware information:**
 - Version: 2.3.5 + 2.3.6
 - MQTT: YES
 - MQTT payload type: [e.g. JSON]
 - HAN GPIO: UART0
 - HAN baud and parity:2400 8E1

**Comment by ArnieO** [comment]
Can you show us screendump of the config screen when it is not working?

**Comment by githubpassera** [comment]
234 Working.
![image](https://github.com/user-attachments/assets/13414f43-cc4e-4064-a5ca-4002622f90e6)
236 Not working
![image](https://github.com/user-attachments/assets/acede379-260d-4a34-81c5-089c3910a0ec)

**Comment by egiljae** [comment]
Also not able to get 2.3.6 working, no HAN data. 2.3.4 works just fine, same config.
![Uploading Screenshot 2024-07-21 at 21.24.32.png…]()

**Comment by egiljae** [comment]
> @egiljae: You are using a device with ethernet, maybe the issue is related to that in some way. I see that you have HAN Rx and HAN Tx on the same GPIO: ![image](https://private-user-images.githubusercontent.com/10295178/350884506-ded1e938-cd5f-4e15-bf53-d6da5ae5c61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzY1NjcsIm5iZiI6MTcyMTYzNjI2NywicGF0aCI6Ii8xMDI5NTE3OC8zNTA4ODQ1MDYtZGVkMWU5MzgtY2Q1Zi00ZTE1LWJmNTMtZDZkYTVhZTVjNjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjlkMzRjZmI2MzFjNmFjMzA3OGVhZWVkYWI3ZWQ2YjcxYWVhYjA0ZGE3ZGQ0YjI3MGQ2NjFjNzVkNmVlZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KNLnDmYBsatELXmgR4YIeW47-_pDjSEVnINaSAmPHT8) That does not look sensible. In most situations you do not need "HAN Tx". Please try to delete it to run v2.3.6 (leave the field empty).

You are correct. Setting HAN TX to something other than GPIO4 works. I could not set it blank, since there is no option for it, neither could I find any reference to it in the config file. I just set it to a GPIO pin that is not in use. The HAN TX field was automatically set after upgrading from an older version.

<img width="598" alt="Screenshot 2024-07-22 at 10 25 27" src="https://github.com/user-attachments/assets/5d3c866f-d8df-46af-b99a-88c61a3025a6">

**Comment by ArnieO** [comment]
> You are correct. Setting HAN TX to something other than GPIO4 works.
(...)
The HAN TX field was automatically set after upgrading from an older version.

I suspected something like that. There are very few users on Ethernet, so feedback is very welcome! 
I will notify @gskjold that there should be an option to set the "HAN Tx" field blank, so that it will be fixed in future revisions.

**Comment by githubpassera** [comment]
Yes, that was the issue, I set the TX to GPIO38 (not used) and 2.3.6 is now working, thank you.
