### ISSUE TITLE
Getting stuck while trying to receive ENTSOE price information 

### ISSUE THREAD

**Issue by bommel947** [UtilitechAS/amsreader-firmware#824]
**Description**
After putting in the ENTSOE token the modul stops while trying to receive the prices for the next day. It gets stuck. The HAN port tag is dark
![image](https://github.com/user-attachments/assets/e6a55d93-0d7a-467a-9133-6e7ebdc70be1)

**Hardware information:**
 - Country: Austria
 - Meter: OmniPower
 - Encryption enabled: no
 - AMS reader: PowK

**Relevant firmware information:**
 - Version: 2.3.6
 - MQTT: yes
 - MQTT payload type: home assistant
 - HAN GPIO: ?
 - HAN baud and parity: 2400
 - Temperature sensors: none
 - ENTSO-E API enabled: yes

If have enabled telnet debug:

```
(I) Successfully connected to MQTT
(I)   Subscribing to [homeassistant/status]
(I) (PriceService) Fetching prices for 31.07.2024
(D) (PriceService)  url: https://web-api.tp.entsoe.eu/api?securityToken=71771941-4be9-4126-ae2a-e01cc4d0b49b&documentType=A44&periodStart=202407302200&periodEnd=202407312200&in_Domain=10YAT-APG------L&out_Domain=10YAT-APG------L

```
no more communiction after that last line.

If i remove the entsoe token and reboot the reader everything is back to normal...

**Comment by ArnieO** [comment]
We have had a lot of issues with the Entso-E API, it does not always respond - leading to a lot of "customer service questions" (like this one). 

The issues with the Entso-E API was the reason we implemented an intermediate server - which is what you read from when you remove the Entso-E token. 

So that is now the recommended method.
